name: Test

on:
  push:
    branches:
      - "**"

jobs:
  rspec:
    name: Rspec
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-retries 5
          --health-timeout 5s

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/feature_flags_test
      RAILS_ENV: test
      RAILS_MASTER_KEY: ${{secrets.RAILS_MASTER_KEY}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare application environment
        uses: ./.github/actions/prepare-app-env

      - name: Setup DB
        run: bin/rails db:test:prepare

      - name: Run tests
        run: bin/rails spec
